### ISSUE TITLE
New Dupe Found | Plugin Compatibility Request

### ISSUE THREAD

**Issue by TheFantasticLoki** [christopherwalkerml/ShulkerPacks#11]
Shulkerpacks does not send new information to PlayerVaultsX both on latest versions.

Recreate Dupe: Simply open a shulker that is inside a playervault and take an item. When you reopen the vault the shulker will still have the items taken before. This also works as an item losing bug if you place items in a shulker that is inside a player vault.

PlayerVaultsX hasn't been updated since Nov 2020 so a fix or compatibility patch will need to come from you.

Currently trying to figure out how to blacklist vaults in the shulkerpack config to avoid this issue

No Errors appear in console.

**Comment by mbax** [comment]
> PlayerVaultsX hasn't been updated since Nov 2020 so a fix or compatibility patch will need to come from you.

Only not updated because one hadn't been necessary. Happy to help to find a solution when I'm home from work.

**Comment by christopherwalkerml** [comment]
ShulkerPacks has a blacklist option in the config. You can put the PlayerVaultsX inventory name there to prevent shulkerboxes from being opened in them.

if this is still an issue with the blacklist feature available, Ill re-open this.

**Comment by mbax** [comment]
Well! That certainly works!

I believe, from checking the source, that with the default config just having `"Vault"` would work and catch everything while not getting in the way of vanilla?

@christopherwalkerml I'm considering adding code to PlayerVaultsX to detect this plugin, check its blacklist to see if it would catch the current PlayerVaultsX title (can be configured by the user), and print a warning to console if it's not covered. Would that be alright with you? :)

**Comment by christopherwalkerml** [comment]
Yes, adding "Vault" to the blacklist would work, as long as PlayerVault's inventory contains the word "Vault".
And I suppose so, it's up to you. I don't see how it could hurt!

**Comment by TheFantasticLoki** [comment]
Yes I figured this out but being able to open up shulkers inside playervaults would be a much nicer solution. This is more of a bandaid solution instead of just adding proper compatibility.

**Comment by mbax** [comment]
"Just" adding compatibility is actually a pretty difficult thing to accomplish. Might become viable after the big update hopefully coming out this summer.
