### ISSUE TITLE
A bow shot is detected as a shulker opening during combat. 

### ISSUE THREAD

**Issue by CraftersX** [christopherwalkerml/ShulkerPacks#14]
A bow shot is detected as a shulker opening during combat. 

https://youtu.be/his6XLq2mPQ

**Comment by CraftersX** [comment]
This is also the case when eating  https://www.youtube.com/watch?v=QwrmxD8UpOM

**Comment by christopherwalkerml** [comment]
Thanks for the report. This should be fixed in the latest version
