### ISSUE TITLE
Opening shulkerbox with right click does not work in crafting table, stonecutter, anvil, etc.

### ISSUE THREAD

**Issue by domisum** [christopherwalkerml/ShulkerPacks#7]
What I expect to happen: Right clicking a shulkerbox in the player inventory while in the interface of crafting table, stonecutter, anvil, etc. should open the shulker box as a backpack.

What happens: The item attaches to the cursor, no shulker box inventory opens.

**Comment by christopherwalkerml** [comment]
Thanks for the report. This should be fixed in the latest patch.
