### ISSUE TITLE
Accessing content when dyeing shulker chest

### ISSUE THREAD

**Issue by Qumoo** [christopherwalkerml/ShulkerPacks#9]
You can access the content of a shulker chest when dyeing in the crafting menu.
![image](https://user-images.githubusercontent.com/76853697/112671533-97d21980-8e62-11eb-954a-d4e1a62be33a.png)

When right-clicking the magenta shulker box you open the shulker menu and can remove the items from the box.
Then when you leave you keep the items you just removed from the shulkerbox and the orange shulker box thus duping the items.

**Comment by christopherwalkerml** [comment]
Hi @Qumoo I can't seem to reproduce this bug, as I already have this implemented in the code:
`if typeStr.equals("WORKBENCH") { return; }`
right here: [ShulkerListener.98](https://github.com/christopherwalkerml/ShulkerPacks/blob/master/src/main/java/me/darkolythe/shulkerpacks/ShulkerListener.java#L98)

**Comment by Qumoo** [comment]
since it is merged I am closing this issue.
thanks for merging.
